# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

workspace 'qr_app'

def core_pod
  target 'Common' do
    project '../Cores/Common/Common.project'
  end

  target 'RouterService' do
    project '../Cores/RouterService/RouterService.project'
  end

  target 'RouterServiceInterface' do
    project '../Cores/RouterServiceInterface/RouterServiceInterface.project'
  end
end

def core_feature
  target 'HomeFeature' do
    project 'HomeFeature/HomeFeature.project'
  end
end

target 'qr_app' do
  
  core_pod
  
  target 'qr_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
